
global:
  # Namespace to deploy the service
  namespace: pzk23
  # ID of NS used to deploy this chart
  nsId: "1234342"

# Name of network-attachment definition associated with macvlan interface
macvlanNetName: "default-macvlan-net1"
# # Namespace associate with above network-attachment definition associated with macvlan interface
macvlanNetNamespace: "default"

replicaCount: "2"

service:
  # Service type
  type: NodeP

metrics:
  enabled: true
  annotations:
    {
      scrape: true,
      path: /api/v1/pong/mics,
      por89
  

# Select the node for NF to run
nodeSelector: {}
