global:
  # Namespace to deploy the service
  namespace: pzk23
  # ID of NS used to deploy this chart
  nsId: "1234342"

replicaCount: "2"

service:
  # Service type
  type: Test

metrics:
  enabled: true
  annotations:
    {
      scrape: true,
      path: /api/v1/pong/metrics,
      port: 18889
    }

# Select the node for NF to run
nodeSelector: {}
