apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-wnsx3yg3v-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: autobot-test25-pzk
      nsId: fd15245f-38c9-4fc3-8a9c-f0c7c6cbde83
    macvlanNetName: defaultcombined1macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
