global:
  # Namespace to deploy the service
  namespace: default

# Name of network-attachment definition associated with macvlan interface
macvlanNetName: "default-macvlan-net1"
# Namespace associate with above network-attachment definition associated with macvlan interface
macvlanNetNamespace: "autobot-test25-pzk"
# Number of pods for the service
replicaCount: "2"

