apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-0mdqwuyi1-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 5a98bcc2-56b4-4711-9b2b-14f65000c985
    macvlanNetName: defaultcombined2macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
