apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-y9rlrbgjw-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: fec23cba-a18d-46d5-ba3f-31cbb21c34a2
    macvlanNetName: defaultcombined2macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '2'
    service:
      type: NodePort
