apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-8vsdmwiq3-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: f0ebd33e-34f5-4f35-8df5-2fd248bbff99
    macvlanNetName: defaultcombined4macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
