apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-y9rlrbgjw-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: c18ace21-eff6-41a0-ab31-6ae0a389ae33
    macvlanNetName: defaultcombined2macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
