apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-y9rlrbgjw-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 5a98bcc2-56b4-4711-9b2b-14f65000c985
    macvlanNetName: defaultcombined2macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
