apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-ivj61fnzj-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: fd15245f-38c9-4fc3-8a9c-f0c7c6cbde83
    macvlanNetName: defaultcombined1macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '2'
    service:
      type: NodePort
